version: "3.9"
services:
  app:
    build: .
    ports: ["8000:8000"]
    environment:
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - S3_ENDPOINT_URL=http://minio:9000
      - STORAGE_DEFAULT_PROVIDER=minio
      - MINIO_ENDPOINT_URL=http://minio:9000
      - MINIO_ACCESS_KEY_ID=minioadmin
      - MINIO_SECRET_ACCESS_KEY=minioadmin
      - MINIO_BUCKET_CSV=onecore-uploads
      - MINIO_BUCKET_DOCS=onecore-documents
      - LOCALSTACK_ENDPOINT_URL=http://localstack:4566
      - LOCALSTACK_ACCESS_KEY_ID=test
      - LOCALSTACK_SECRET_ACCESS_KEY=test
      - LOCALSTACK_BUCKET_CSV=onecore-uploads-localstack
      - LOCALSTACK_BUCKET_DOCS=onecore-documents-localstack
    env_file: .env
    depends_on: [sqlserver, minio, localstack]

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_DB: "prueba_tecnica"
    ports: ["1433:1433"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports: ["9000:9000", "9001:9001"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  localstack:
    image: localstack/localstack:3.0.2
    ports: ["4566:4566"]
    environment:
      - SERVICES=s3
      - DEBUG=1
